runners:
  - name: azure-windows-runner
    cloud: azure
    region: uksouth
    instance_type: Standard_D2s_v3
    machine_image: "MicrosoftWindowsServer:WindowsServer:2022-datacenter-azure-edition:latest"
    labels:
      - cirun-runner
    extra_config:
      licenseType: "Windows_Server"
      storageProfile:
        osDisk:
          diskSizeGB: 512