runners:
  - name: "azure-windows-runner"
    cloud: "azure"
    region: "uksouth"
    instance_type: "Standard_D2s_v3"
    machine_image:
      publisher: microsoftwindowsdesktop
      offer: windows-11
      sku: win11-22h2-pro
      version: latest
    labels:
      - "cirun-azure-windows-runner"
