# This is a basic workflow running on Azure cloud
name: Cirun Runner

on:
  push

jobs:
  build:
    permissions: write-all
    runs-on: "cirun-runner--${{ github.run_id }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0

      - name: systeminfo
        run: systeminfo

      - name: Run ls and pwd
        run: |
          ls
          pwd

      - name: Get-Disk
        run: Get-Disk
                  